name: Build App
on: [push, workflow_dispatch]
jobs:
  Build-App:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update Secrets
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
        run: |
          sed -i "" "s/amplitudeApiKey = \"Your App Secret\"/amplitudeApiKey = \"${AMPLITUDE_API_KEY}\"/" "FurAffinity/Secrets.swift"
          sed -i "" "s/PRODUCT_BUNDLE_IDENTIFIER = com.example.id1234;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/" "FurAffinity.xcodeproj/project.pbxproj"
      - uses: mxcl/xcodebuild@v3
        with:
          action: none
          xcode: ~16.0
          code-sign-certificate: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          code-sign-certificate-passphrase: ${{ secrets.P12_PASSWORD }}
          mobile-provisioning-profiles-base64: |
            ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      - name: Build App
        run: |
          xcodebuild -disableAutomaticPackageResolution -scheme FurAffinity -destination 'platform=iOS Simulator,name=iPhone 15' -configuration Release build
      - name: Run Tests
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          qualified_app_name="FurAffinity-${GITHUB_REF_NAME}-${git_hash}"
          results_path=$(pwd)/${qualified_app_name}.xcresult
          xcodebuild -disableAutomaticPackageResolution -scheme FurAffinity -destination 'platform=iOS Simulator,name=iPhone 15' -resultBundlePath "${results_path}" test
          zip -r "${qualified_app_name}.xcresult.zip" "${qualified_app_name}.xcresult"
      - name: Upload Tests Results
        uses: actions/upload-artifact@v4
        with:
          name: Xcode Test Results
          path: ./*.xcresult
          if-no-files-found: error
