name: Create Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build-App:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update Secrets
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
        run: |
          sed -i "" "s/amplitudeApiKey = \"Your App Secret\"/amplitudeApiKey = \"${AMPLITUDE_API_KEY}\"/" "FurAffinity/Secrets.swift"
          sed -i "" "s/PRODUCT_BUNDLE_IDENTIFIER = com.example.id1234;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/" "FurAffinity.xcodeproj/project.pbxproj"
      - name: Archive App
        uses: mxcl/xcodebuild@v3
        with:
          action: none
          xcode: ~16.0
          authentication-key-base64: ${{ secrets.APP_STORE_CONNECT_KEY_BASE64 }}
          authentication-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          authentication-key-issuer-id: ${{ secrets.APP_STORE_CONNECT_KEY_ISSUER_ID }}
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          qualified_app_name="FurAffinity-${GITHUB_REF_NAME}-${git_hash}"
          archive_path=$(pwd)/${qualified_app_name}.xcarchive
          xcodebuild -disableAutomaticPackageResolution -scheme FurAffinity -destination generic/platform=iOS -configuration Release archive -archivePath "${archive_path}" -allowProvisioningUpdates
          mkdir Payload
          cp -Rp ${archive_path}/Products/Applications/* Payload/
          zip -r "${qualified_app_name}.ipa" Payload
          zip -r "${qualified_app_name}.xcarchive.zip" "${qualified_app_name}.xcarchive"
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: IPA
          path: FurAffinity-*.ipa
          if-no-files-found: error
      - name: Upload xcarchive
        uses: actions/upload-artifact@v4
        with:
          name: Xcode Archive
          path: ./*.xcarchive
          if-no-files-found: error
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          name: FurAffinity ${{ github.ref_name }}
          artifacts: FurAffinity-*.ipa,*.xcarchive.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          draft: true
